# Copy from BB's blog XD
dist: xenial
branches:
  only:
    - master

language: go

install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

script:
  - HUGO_ENV=production hugo --gc --minify -v


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master

notifications:
  email:
      recipients:
        - 2qbingxuan@gmail.com
      on_success: always
      on_failure: always
